export const PET_NAME_SETTED = 'PET_NAME_SETTED';
export const PET_TAG_NUMBER_SETTED = 'PET_TAG_NUMBER_SETTED';

export const GET_PET_TAG_ATTEMPTED = 'GET_PET_TAG_ATTEMPTED';
export const GET_PET_TAG_DONE = 'GET_PET_TAG_DONE';
export const GET_PET_TAG_FAILED = 'GET_PET_TAG_FAILED';

export const SET_PET_TAG_ATTEMPTED = 'SET_PET_TAG_ATTEMPTED';
export const SET_PET_TAG_DONE = 'SET_PET_TAG_DONE';
export const SET_PET_TAG_FAILED = 'SET_PET_TAG_FAILED';
